---

- name: start mongodb service
  command: 'kubectl create -f {{ role_path }}/files/mongodb_service.yaml -n {{ db_mongodb_namespace }}'

- name: get pod names
  command: 'kubectl get pods -l {{ db_mongodb_podlabel }} -n {{ db_mongodb_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: wait for mongodb pods to be ready
  command: 'kubectl wait --for=condition=Ready pod/{{ item }} -n {{ db_mongodb_namespace }} --timeout={{ db_mongodb_timetoready_sec }}s'
  with_items: "{{ podlist.stdout_lines }}"

...
