---

- name: get pod name
  command: 'kubectl get pods -l {{ bench_ycsb_podlabel }} -n {{ bench_ycsb_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: create directory for storing pod output
  file: 
    path: '{{ bench_ycsb_dir }}/{{ podlist.stdout }}'
    state: directory

- name: fetch output from pod
  command: 'kubectl cp {{ bench_ycsb_namespace }}/{{ podlist.stdout }}:{{ bench_ycsb_podoutdir }} {{ bench_ycsb_dir }}/{{ podlist.stdout }}'

- name: get pod location
  shell: 'kubectl get pods -l {{ bench_ycsb_podlabel }} -n {{ bench_ycsb_namespace }} -o wide >> {{ bench_ycsb_pdir }}/out.{{ role_name }}.txt'

- include_role:
    name: '{{ bench_ycsb_dbrole }}'
  vars:
    db_mode: gather

...
