---

#
# variables similar to the below are likely to be present in different bench roles
#

# output directory for run
bench_ycsb_pdir: '{{ run_dir }}'

# directory for role's output
bench_ycsb_dir: '{{ run_dir }}/{{ role_name }}'

# namespace
bench_ycsb_namespace: '{{ run_namespace }}'

# label on pods
bench_ycsb_podlabel: "type=benchmark-pod"

# directory where output files exist in pods/containers
bench_ycsb_podoutdir: /benchout

# main container name
bench_ycsb_container: "benchmark-complete"

# configmap to trigger benchmark phase transition
bench_ycsb_configmap: "bench-ycsb-cfgmap"
bench_ycsb_mapkey: "bench.phase"
bench_ycsb_initphase: "prepare"
bench_ycsb_nextphase: "run"

# sequence number of prepwait initContainer
bench_ycsb_prepc: 2

# expected time for prepare phase
bench_ycsb_prep_sec: 60

# time between retries waiting for prepare phase completion
bench_ycsb_prepretry_sec: 60

# number of retries waiting for prepare phase completion
bench_ycsb_prep_retries: 60

# maximum time for a run; used for wait timeout
bench_ycsb_maxtime_sec: 36000

#
# variables likely to be specific to this benchmark
#

# nosql db to run against; specify role
bench_ycsb_dbrole: db_mongodb

# nosql db as specified on ycsb command line
bench_ycsb_nosqldb: mongodb

# name of collection/table/db as specified on ycsb command line
bench_ycsb_storename: ycsb

# TODO: these need to be generated, not hard-coded
bench_ycsb_db_loadopts: "mongodb.url='mongodb://mongo-0.mongo:27017/ycsb?w=0'"
bench_ycsb_db_runopts: "mongodb.url='mongodb://mongo-0.mongo:27017/ycsb'"

# ycsb workload to run
bench_ycsb_workload: "workloads/workloada"

# number of records created in load phase
bench_ycsb_reccount: 1000000

# number of records accessed in run phase
bench_ycsb_opcount: 500000

# number of threads in load phase
bench_ycsb_load_thrds: 16

# number of threads in run phase
bench_ycsb_run_thrds: 8

...
