
---
# quickly test a particular role

- hosts: localhost
  vars:
    calm_role: calm_fioiops
    run_dir: /tmp/run_ts
    run_namespace: nm-kubuculum
    run_storageclass: ocs-storagecluster-ceph-rbd

  tasks:

  - name: create namespace for run
    command: 'kubectl create namespace {{ run_namespace }}'

  - name: create run directory
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: start

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: ensure_ready

  - pause:
      seconds: 300

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: gather

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: stop

  - name: delete run namespace
    command: 'kubectl delete namespace {{ run_namespace }}'

...
