
---
# quickly test a particular role

- hosts: localhost

  tasks:

  - name: set calm role to be tested
    set_fact:
      calm_role: calm_fioiops

  - name: set run directory
    set_fact:
      run_dir: /tmp/run_ts

  - name: set namespace for run
    set_fact:
      run_namespace: nm-kubuculum

  - name: create namespace for run
    command: 'kubectl create namespace {{ run_namespace }}'

  - name: create run directory
    local_action:
      module: file
      path: '{{ run_dir }}'
      state: directory

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: start

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: ensure_ready

  - pause:
      seconds: 300

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: gather

  - include_role:
      name: '{{ calm_role }}'
    vars:
      calm_mode: stop

  - name: delete run namespace
    command: 'kubectl delete namespace {{ run_namespace }}'

...
