---
# defaults file for db_mongodb

# default namespace
db_mongodb_namespace: '{{ run_namespace }}'

# label on pods
db_mongodb_podlabel: "role=mongo"

# name of container in mongodb pod
db_mongodb_container: "mongo"

# max time to wait for mongo pods ready
db_mongodb_timetoready_sec: 600

...
