---
apiVersion: batch/v1
kind: Job
metadata:
  name: ycsb
spec:
  template:
    metadata:
      labels:
        type: benchmark-pod
    spec:
      volumes:
      - name: output-volume
        emptyDir: {}
      containers:
      - name: benchmark-complete
        image: rhel7
        volumeMounts:
          - mountPath: /benchout
            name: output-volume
        command: ["/bin/sh"]
        args: ["-c", "touch /benchout/benchmark.completed.txt; sleep 3600"]
      initContainers:
      - name: ycsb-load
        image: quay.io/mpillai/ycsb
        volumeMounts:
          - mountPath: /benchout
            name: output-volume
        command: ["/bin/sh"]
        args: 
          - "-c"
          - >
            cd /ycsb/ycsb-latest 
            ; bin/ycsb load mongodb -s 
            -P workloads/workloadc
            -p mongodb.url='mongodb://mongo-0.mongo:27017/ycsb?w=0'
            -p recordcount=100000000
            -threads 16 
            2>&1 | tee /benchout/ycsb.load.txt
      - name: ycsb-run
        image: quay.io/mpillai/ycsb
        volumeMounts:
          - mountPath: /benchout
            name: output-volume
        command: ["/bin/sh"]
        args: 
          - "-c"
          - >
            cd /ycsb/ycsb-latest 
            ; bin/ycsb run mongodb -s 
            -P workloads/workloadc 
            -p mongodb.url='mongodb://mongo-0.mongo:27017/ycsb'
            -p recordcount=100000000
            -p operationcount=10000000
            -threads 32
            2>&1 | tee /benchout/ycsb.run.txt
      restartPolicy: Never
...
