---

- name: get list of pods
  command: 'kubectl get pods -l {{ calm_fioiops_podlabel }} -n {{ calm_fioiops_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: create per-pod directory for storing output
  file:
    path: '{{ calm_fioiops_dir }}/{{ item }}'
    state: directory
  with_items: "{{ podlist.stdout_lines }}"

- name: fetch output from pods
  command: 'kubectl cp {{ calm_fioiops_namespace }}/{{ item }}:{{ calm_fioiops_podoutdir }} {{ calm_fioiops_dir }}/{{ item }}'
  with_items: "{{ podlist.stdout_lines }}"

- name: get pod locations
  shell: 'kubectl get pods -l {{ calm_fioiops_podlabel }} -n {{ calm_fioiops_namespace }} -o wide >> {{ run_dir }}/out.{{ role_name }}.txt'

...
