---
# defaults file for bench_fiorand

# default namespace
bench_fiorand_namespace: '{{ benchmark_namespace }}'

# label on pods
bench_fiorand_podlabel: "type=benchmark-pod"

# directory where output files exist in pods/containers
bench_fiorand_podoutdir: /benchout

# main container name
bench_fiorand_container: "benchmark-complete"

# maximum time for a run; used for wait timeout
bench_fiorand_maxtime_sec: 36000

# pvc size; limit on data set size
bench_fiorand_pvcsize_gb: 8

# block size for initial write`
bench_fiorand_sbs_kb: 128

# block size for random IO
bench_fiorand_bs_kb: 4

# file size per job
bench_fiorand_fsz_gb: 2

# number of jobs
bench_fiorand_njobs: 2

# iodepth per job
bench_fiorand_iodepth: 32

# run time for time based job
bench_fiorand_run_sec: 60
...
