---

#
# most roles have variables similar to the below
#

# output directory for run
bench_fiorand_pdir: '{{ run_dir }}'

# directory for role's output
bench_fiorand_dir: '{{ run_dir }}/{{ role_name }}'

# namespace
bench_fiorand_namespace: '{{ run_namespace }}'

# bench_fiorand_storageclass: 
#   if bench_fiorand_storageclass is defined that is used
#   else if run_storageclass is defined that is used
#   else default storage class is used

# label on pods
bench_fiorand_preppodlabel: "type=benchmark-prep-pod"
bench_fiorand_podlabel: "type=benchmark-pod"

# nodeSelector, for fio client pod
# bench_fiorand_nodelabel="node-role.kubernetes.io/worker=''"

# nodeSelector, for fio server pods, in distributed mode
# bench_fiorand_servernodelabel="node-role.kubernetes.io/worker=''"

# directory where output files exist in pods/containers
bench_fiorand_podoutdir: /benchout

# directory where data set is created, when not in distributed mode
bench_fiorand_datadir: /dataset

# main container name
bench_fiorand_container: "benchmark-complete"

# maximum time for a run; used for wait timeout
bench_fiorand_maxtime_sec: 36000

#
# variables likely to be specific to this benchmark
#

# mode: is this fio in distributed mode, aka client-server mode
bench_fiorand_distributed: True

# allow tests to be optional
bench_fiorand_testread: True
bench_fiorand_testwrite: True

# calculate pvc size instead of relying on user input
bench_fiorand_pvc_scalefactor: 2 # multiply required data set size by this 
bench_fiorand_pvc_extra_gb: 32 # add this extra space

# block size for initial write
bench_fiorand_sbs_kb: 1024

# block size for random IO
bench_fiorand_bs_kb: 8

# file size per job
bench_fiorand_fsz_gb: 2

# number of jobs
bench_fiorand_njobs: 2

# iodepth per job
bench_fiorand_iodepth: 32

# run time for time based job
bench_fiorand_run_sec: 60

# number of fio instances, for distributed mode
bench_fiorand_ninstances: 1

...
