---

- name: get list of sysstat pods
  command: 'kubectl get pods -l {{ stats_sysstat_podlabel }} -n {{ stats_sysstat_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: create per-pod directory for storing output
  file:
    path: '{{ stats_sysstat_dir }}/{{ item }}'
    state: directory
  with_items: "{{ podlist.stdout_lines }}"

- name: fetch output from pods
  command: 'kubectl cp {{ stats_sysstat_namespace }}/{{ item }}:{{ stats_sysstat_podoutdir }} {{ stats_sysstat_dir }}/{{ item }}'
  with_items: "{{ podlist.stdout_lines }}"

- name: collect df output from pods
  shell: 'kubectl exec {{ item }} -n {{ stats_sysstat_namespace }} -- df -h > {{ stats_sysstat_dir }}/{{ item }}/df_h.txt'
  with_items: "{{ podlist.stdout_lines }}"

- name: get pod locations
  shell: 'kubectl get pods -l {{ stats_sysstat_podlabel }} -n {{ stats_sysstat_namespace }} -o wide >> {{ run_dir }}/out.{{ role_name }}.txt'
...
