---

- name: stop fio pod
  command: 'kubectl delete -f {{ bench_fioforsql_dir }}/fiorun_job.yaml -n {{ bench_fioforsql_namespace }}'

- name: delete fio pvc
  command: 'kubectl delete -f {{ bench_fioforsql_dir }}/fiopvc.yaml -n {{ bench_fioforsql_namespace }}'

...
