---

- name: get fio pod name
  command: 'kubectl get pods -l {{ bench_fioforsql_podlabel }} --namespace={{ bench_fioforsql_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: create directory for storing fio pod output
  file: 
    path: '{{ bench_fioforsql_dir }}/{{ podlist.stdout }}'
    state: directory

- name: fetch output from fio pod
  command: 'kubectl cp {{ bench_fioforsql_namespace }}/{{ podlist.stdout }}:{{ bench_fioforsql_podoutdir }} {{ bench_fioforsql_dir }}/{{ podlist.stdout }}'

- name: fetch df from fio pod
  shell: 'kubectl exec {{ podlist.stdout }} -c {{ bench_fioforsql_container }} -n {{ bench_fioforsql_namespace }} -- df -h > {{ bench_fioforsql_dir }}/{{ podlist.stdout }}/df_h.txt'

- name: fetch mount from fio pod
  shell: 'kubectl exec {{ podlist.stdout }} -c {{ bench_fioforsql_container }} -n {{ bench_fioforsql_namespace }} -- mount > {{ bench_fioforsql_dir }}/{{ podlist.stdout }}/mount.txt'

- name: get fio pod location
  shell: 'kubectl get pods -l {{ bench_fioforsql_podlabel }} -n {{ bench_fioforsql_namespace }} -o wide >> {{ bench_fioforsql_pdir }}/out.{{ role_name }}.txt'

...
