---
- name: create fiorun job file from template
  template:
    src: '{{ role_path }}/templates/fiorun_job.j2'
    dest: '{{ bench_fioforsql_dir }}/fiorun_job.yaml'

- name: create fiorun pod
  command: 'kubectl create -f {{ bench_fioforsql_dir }}/fiorun_job.yaml -n {{ bench_fioforsql_namespace }}'

- name: get fio pod name
  command: 'kubectl get pods -l {{ bench_fioforsql_podlabel }} --namespace={{ bench_fioforsql_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: wait for fio test completion
  command: 'kubectl wait --for=condition=Ready pod/{{ podlist.stdout }} --namespace={{ bench_fioforsql_namespace }} --timeout={{ bench_fioforsql_maxtime_sec }}s'

...
