---

- name: stop fio pod
  command: 'kubectl delete -f {{ bench_fiorand_dir }}/fio_job.yaml -n {{ bench_fiorand_namespace }}'

- name: delete benchmark configmap
  command: 'kubectl delete configmap {{ bench_fiorand_configmap }} -n {{ bench_fiorand_namespace }}'

...
