---
# tasks file for bench_fiorand start

- name: create directory for storing bench_fiorand output
  file:
    path: '{{ run_dir }}/{{ role_name }}'
    state: directory

- name: create configmap
  command: 'kubectl create configmap kubuculum-state --from-literal=bench.mode=prepare -n {{ bench_fiorand_namespace }}'

- name: create job file from template
  template:
    src: '{{ role_path }}/templates/fio_job.j2'
    dest: '{{ run_dir }}/{{ role_name }}/fio_job.yaml'

- name: start fio pod
  command: 'kubectl create -f {{ run_dir }}/{{ role_name }}/fio_job.yaml --namespace={{ bench_fiorand_namespace }}'

- name: get fio pod name
  command: 'kubectl get pods -l {{ bench_fiorand_podlabel }} --namespace={{ bench_fiorand_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

# first initContainer completion marks end of prepare phase
- name: wait for fio prepare phase completion
  shell: "kubectl describe pod {{ item }} -n {{ bench_fiorand_namespace }} | grep State: | head -n 1 | awk '{print $2}'"
  register: containerstate
  until: containerstate.stdout.find("Terminated") != -1
  retries: 60
  delay: 60
  with_items: "{{ podlist.stdout_lines }}"
...
