---

#
# most roles have variables similar to the below
#

# output directory for run
bench_fioseq_pdir: '{{ run_dir }}'

# directory for role's output
bench_fioseq_dir: '{{ run_dir }}/{{ role_name }}'

# namespace
bench_fioseq_namespace: '{{ run_namespace }}'

# bench_fioseq_storageclass: 
#   if bench_fioseq_storageclass is defined that is used
#   else if run_storageclass is defined that is used
#   else default storage class is used

# label on pods
bench_fioseq_wpodlabel: "type=fio-seqwr-pod"
bench_fioseq_rpodlabel: "type=fio-seqrd-pod"

# optional nodeSelector, for fio client pods
# bench_fioseq_nodelabel="node-role.kubernetes.io/worker=''"

# optional nodeSelector, for fio server pods
#
# bench_fioseq_servernodelabel="node-role.kubernetes.io/worker=''"

# directory where output files exist in pods/containers
bench_fioseq_podoutdir: /benchout

# main container name
bench_fioseq_container: "benchmark-complete"

# maximum time for a run; used for wait timeout
bench_fioseq_maxtime_sec: 36000

#
# variables likely to be specific to this benchmark
#

# prefer to calculate pvc size instead of relying on user input
bench_fioseq_pvcsz_scalefactor: 2 # multiply required data set size by this 
bench_fioseq_pvcsz_extra_gb: 32 # add this extra space
# bench_fioseq_pvcsz_req_gb: 8 # use this variable to specify size manually

# block size
bench_fioseq_bs_kb: 128

# file size per job
bench_fioseq_fsz_gb: 2

# number of jobs
bench_fioseq_njobs: 2

# number of fio instances
bench_fioseq_ninstances: 1

...
