---

- name: get pod names 
  command: 'kubectl get pods -l {{ os_rootpods_podlabel }} -n {{ os_rootpods_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: drop kernel caches 
  block:
    - shell: 'date >> {{ os_rootpods_dir }}/drop_caches.start.txt'
    - shell: 'kubectl exec {{ item }} -n {{ os_rootpods_namespace }} -- sync; sysctl vm.drop_caches=3'
      with_items: "{{ podlist.stdout_lines }}"
    - shell: 'date >> {{ os_rootpods_dir }}/drop_caches.finish.txt'
  when: podlist.stdout_lines != ""

...
