---
- name: stop pods
  command: 'kubectl delete -f {{ server_fio_dir }}/fioserver_statefulset.yaml -n {{ server_fio_namespace }}'

- name: get pvc names
  command: 'kubectl get pvc -l {{ server_fio_podlabel }} -n {{ server_fio_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: pvclist

- name: delete pvcs 
  command: 'kubectl delete pvc {{ item }} -n {{ server_fio_namespace }}'
  with_items: "{{ pvclist.stdout_lines }}"

...
