---

- set_fact:
    bench_fioseq_test: seqwr
    bench_fioseq_podlabel: "{{ bench_fioseq_wpodlabel }}"

- include_tasks: run_test.yml

- include_role:
    name: util_dropcaches

- set_fact:
    bench_fioseq_test: seqrd
    bench_fioseq_podlabel: "{{ bench_fioseq_rpodlabel }}"

- include_tasks: run_test.yml

...
