---

#
# most roles have variables similar to the below
#

# output directory for run
server_fio_pdir: '{{ run_dir }}'

# directory for role's output
server_fio_dir: '{{ server_fio_pdir }}/{{ role_name }}'

# namespace
server_fio_namespace: '{{ run_namespace }}'

# server_fio_storageclass: 
#   if server_fio_storageclass is defined that is used
#   else if run_storageclass is defined that is used
#   else default storage class is used

# label on pods
server_fio_podlabel: "role=server-fio"

# for nodeSelector, use something like below:
# server_fio_nodelabel="node-role.kubernetes.io/worker=''"

# main container name
server_fio_container: "fio-server"

# used for wait timeout
server_fio_wait_sec: 600

#
# variables likely to be specific to this benchmark
#

# number of instances
server_fio_nservers: 1

# pvc size; limit on data set size
server_fio_pvcsize_gb: 8

# data set created here
server_fio_datadir: "/dataset"

# generated comma separated list of the form:
#   server-fio-0.server-fio,server-fio-1.server-fio
# server_fio_serverlist: "server-fio-0.server-fio"

# port, fio default
server_fio_port: 8765

...
