---
# tasks file for prepare phase

- name: create directory for storing role output
  file:
    path: '{{ bench_fioforsql_dir }}'
    state: directory

- set_fact:
    bench_fioforsql_storageclass: '{{ run_storageclass }}'
  when: bench_fioforsql_storageclass is not defined and run_storageclass is defined

- name: create pvc yaml from template
  template:
    src: '{{ role_path }}/templates/fiopvc.j2'
    dest: '{{ bench_fioforsql_dir }}/fiopvc.yaml'

- name: create job file from template
  template:
    src: '{{ role_path }}/templates/fioprep_job.j2'
    dest: '{{ bench_fioforsql_dir }}/fioprep_job.yaml'

- name: create pvc
  command: 'kubectl create -f {{ bench_fioforsql_dir }}/fiopvc.yaml -n {{ bench_fioforsql_namespace }}'

- name: create fioprep pod
  command: 'kubectl create -f {{ bench_fioforsql_dir }}/fioprep_job.yaml -n {{ bench_fioforsql_namespace }}'

- name: get pod name
  command: 'kubectl get pods -l {{ bench_fioforsql_preppodlabel }} --namespace={{ bench_fioforsql_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: wait for fio prepare phase completion
  command: 'kubectl wait --for=condition=Ready pod/{{ podlist.stdout }} --namespace={{ bench_fioforsql_namespace }} --timeout={{ bench_fioforsql_maxtime_sec }}s'

- name: create directory for storing fioprep pod output
  file: 
    path: '{{ bench_fioforsql_dir }}/prepare_{{ podlist.stdout }}'
    state: directory

- name: fetch output from fioprep pod
  command: 'kubectl cp {{ bench_fioforsql_namespace }}/{{ podlist.stdout }}:{{ bench_fioforsql_podoutdir }} {{ bench_fioforsql_dir }}/prepare_{{ podlist.stdout }}'

- name: delete fioprep pod
  command: 'kubectl delete -f {{ bench_fioforsql_dir }}/fioprep_job.yaml -n {{ bench_fioforsql_namespace }}'
...
