---
# tasks file for create_rundir

- name: get current directory
  run_once: true
  local_action:
    module: command
    args: pwd
  register: create_rundir_cwd

- name: set base directory
  set_fact:
    create_rundir_pdir: "{{ run_basedir | default(create_rundir_cwd.stdout) }}"

- name: generate run timestamp
  run_once: true
  local_action:
    module: shell
    args: 'date +%F_%s'
  register: create_rundir_ts

- name: set run directory
  set_fact:
    run_dir: '{{ create_rundir_pdir }}/run_{{ create_rundir_ts.stdout }}'

- name: create run directory
  run_once: true
  local_action:
    module: file
    path: '{{ run_dir }}'
    state: directory
...
