---
# tasks file for prepare phase

- name: create directory for storing role output
  file:
    path: '{{ bench_fiorand_dir }}'
    state: directory

- set_fact:
    bench_fiorand_storageclass: '{{ run_storageclass }}'
  when: bench_fiorand_storageclass is not defined and run_storageclass is defined

- name: create pvc yaml from template
  template:
    src: '{{ role_path }}/templates/fiopvc.j2'
    dest: '{{ bench_fiorand_dir }}/fiopvc.yaml'

- name: create job file from template
  template:
    src: '{{ role_path }}/templates/fioprep_job.j2'
    dest: '{{ bench_fiorand_dir }}/fioprep_job.yaml'

- name: create pvc
  command: 'kubectl create -f {{ bench_fiorand_dir }}/fiopvc.yaml -n {{ bench_fiorand_namespace }}'

- name: create fioprep pod
  command: 'kubectl create -f {{ bench_fiorand_dir }}/fioprep_job.yaml -n {{ bench_fiorand_namespace }}'

- name: get pod name
  command: 'kubectl get pods -l {{ bench_fiorand_preppodlabel }} --namespace={{ bench_fiorand_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: wait for fio prepare phase completion
  command: 'kubectl wait --for=condition=Ready pod/{{ podlist.stdout }} --namespace={{ bench_fiorand_namespace }} --timeout={{ bench_fiorand_maxtime_sec }}s'

- name: create directory for storing fioprep pod output
  file: 
    path: '{{ bench_fiorand_dir }}/prepare_{{ podlist.stdout }}'
    state: directory

- name: fetch output from fioprep pod
  command: 'kubectl cp {{ bench_fiorand_namespace }}/{{ podlist.stdout }}:{{ bench_fiorand_podoutdir }} {{ bench_fiorand_dir }}/prepare_{{ podlist.stdout }}'

- name: delete fioprep pod
  command: 'kubectl delete -f {{ bench_fiorand_dir }}/fioprep_job.yaml -n {{ bench_fiorand_namespace }}'
...
