---
# tasks file for util_dropcaches

- include_role: 
    name: storage_ceph
  vars: 
    action: drop_caches
  when: ceph_benchrun is defined and ceph_benchrun and util_dropcaches_ceph

- include_role: 
    name: os_rootpods
  vars: 
    action: drop_caches
  when: deploy_osrootpods is defined and deploy_osrootpods and util_dropcaches_os

...
