---
# tasks file for util_dropcaches

- include_role: 
    name: storage_ceph
  vars: 
    action: drop_caches
  when: ceph_benchrun is defined and ceph_benchrun

- include_role: 
    name: stats_sysstat
  vars: 
    stats_mode: drop_caches
  when: stats_enabled is defined and stats_enabled and "stats_sysstat" in stats_role 

...
