---

- name: create namespace
  command: 'kubectl create namespace {{ run_namespace }}'

- name: create role yaml from template
  template:
    src: '{{ role_path }}/templates/kubuculum_role.j2'
    dest: '/tmp/kubuculum_role.yaml'

- name: create role
  command: 'kubectl create -f /tmp/kubuculum_role.yaml'

- name: create role binding yaml from template
  template:
    src: '{{ role_path }}/templates/kubuculum_rolebinding.j2'
    dest: '/tmp/kubuculum_rolebinding.yaml'

- name: create role binding
  command: 'kubectl create -f /tmp/kubuculum_rolebinding.yaml'

...
