---

- name: create directory for storing stats_sysstat output
  file: 
    path: '{{ stats_sysstat_dir }}'
    state: directory
  
- name: create job file from template
  template:
    src: '{{ role_path }}/templates/sysstat_daemonset.j2'
    dest: '{{ stats_sysstat_dir }}/sysstat_daemonset.yaml'

- name: start sysstat pods
  command: 'kubectl create -f {{ stats_sysstat_dir }}/sysstat_daemonset.yaml -n {{ stats_sysstat_namespace }}'

# NOTE: 
#   checking whether all pods in a daemonset are ready, proved
#   to be a little tricky. Using a sleep for now. Nothing bad
#   should happen even if we cross this point prematurely.
- name: wait for all pods to start
  command: 'sleep 30'

...
