---

- name: create directory for storing stats_sysstat output
  file: 
    path: '{{ stats_sysstat_dir }}'
    state: directory
  
- name: create job file from template
  template:
    src: '{{ role_path }}/templates/sysstat_daemonset.j2'
    dest: '{{ stats_sysstat_dir }}/sysstat_daemonset.yaml'

- name: start sysstat pods
  command: 'kubectl create -f {{ stats_sysstat_dir }}/sysstat_daemonset.yaml -n {{ stats_sysstat_namespace }}'

# MTP_TODO
- name: wait for sysstat pods to come up
  command: 'sleep 30'
...
