---

- name: stop fio pod
  command: 'kubectl delete -f {{ bench_ycsb_dir }}/ycsbrun_job.yaml -n {{ bench_ycsb_namespace }}'

- include_role:
    name: '{{ bench_ycsb_dbrole }}'
  vars:
    db_mode: stop

...
