---

- include_role:
    name: '{{ bench_ycsb_dbrole }}'

- name: create directory for storing bench_ycsb output
  file:
    path: '{{ run_dir }}/{{ role_name }}'
    state: directory

- name: create ycsb yaml file from template
  template:
    src: '{{ role_path }}/templates/ycsb_job.j2'
    dest: '{{ run_dir }}/{{ role_name }}/ycsb_job.yaml'

- name: start ycsb pod
  command: 'kubectl create -f {{ run_dir }}/{{ role_name }}/ycsb_job.yaml --namespace={{ bench_ycsb_namespace }}'

- name: sleep for estimated prepare phase time
  command: 'sleep {{ bench_ycsb_prep_sec }}'

- name: get ycsb pod name
  command: 'kubectl get pods -l {{ bench_ycsb_podlabel }} --namespace={{ bench_ycsb_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

# first initContainer completion marks end of prepare phase
- name: wait for prepare phase completion
  shell: "kubectl describe pod {{ item }} -n {{ bench_ycsb_namespace }} | grep State: | head -n 1 | awk '{print $2}'"
  register: cs
  until: cs.stdout.find("Terminated") != -1
  retries: '{{ bench_ycsb_prep_retries }}'
  delay: '{{ bench_ycsb_prepretry_sec }}'
  with_items: "{{ podlist.stdout_lines }}"

...
