---

- name: create ycsb job file from template
  template:
    src: '{{ role_path }}/templates/ycsbrun_job.j2'
    dest: '{{ bench_ycsb_dir }}/ycsbrun_job.yaml'

- name: create ycsb pod
  command: 'kubectl create -f {{ bench_ycsb_dir }}/ycsbrun_job.yaml -n {{ bench_ycsb_namespace }}'

- name: get pod name
  command: 'kubectl get pods -l {{ bench_ycsb_podlabel }} -n {{ bench_ycsb_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: wait for test completion
  command: 'kubectl wait --for=condition=Ready pod/{{ podlist.stdout }} -n {{ bench_ycsb_namespace }} --timeout={{ bench_ycsb_maxtime_sec }}s'

...
