---
# tasks file for bench_ycsb stop

- name: stop ycsb pod
  command: 'kubectl delete -f {{ role_path }}/files/ycsb_job.yaml --namespace={{ bench_ycsb_namespace }}'

- include_role:
    name: '{{ bench_ycsb_db }}'
...
