---

- set_fact:
    bench_fioseq_storageclass: '{{ run_storageclass }}'
  when: bench_fioseq_storageclass is not defined and run_storageclass is defined

- set_fact:
    server_fio_storageclass: '{{ bench_fioseq_storageclass }}'
  when: bench_fioseq_storageclass is defined

- set_fact:
    server_fio_nodelabel: '{{ bench_fioseq_servernodelabel }}'
  when: bench_fioseq_servernodelabel is defined

# calculate per-server space requirement
- set_fact:
    bench_fioseq_pvcsz_req_gb: "{{ bench_fioseq_pvcsz_scalefactor * bench_fioseq_njobs * bench_fioseq_fsz_gb + bench_fioseq_pvcsz_extra_gb }}"
  when: bench_fioseq_pvcsz_req_gb is not defined

- include_role:
    name: server_fio
  vars:
    server_mode: start
    server_fio_namespace: '{{ bench_fioseq_namespace }}'
    server_fio_nservers: '{{ bench_fioseq_ninstances }}'
    server_fio_pvcsize_gb: '{{ bench_fioseq_pvcsz_req_gb }}'

- set_fact:
    bench_fioseq_datadir: '{{ server_fio_datadir }}'
    bench_fioseq_serverlist: '{{ server_fio_serverlist.split(",") }}'

- name: create directory for storing role output
  file:
    path: '{{ bench_fioseq_dir }}'
    state: directory

# nothing else to do as part of prepare
# benchmark tasks are all in run phase

...
