---

- name: create job yaml from template
  template:
    src: '{{ role_path }}/templates/fio_job.j2'
    dest: '{{ bench_fioseq_dir }}/fio_{{ bench_fioseq_test }}_job.yaml'

- name: create pod
  command: 'kubectl create -f {{ bench_fioseq_dir }}/fio_{{ bench_fioseq_test }}_job.yaml -n {{ bench_fioseq_namespace }}'

- name: get fio pod name
  command: 'kubectl get pods -l {{ bench_fioseq_podlabel }} -n {{ bench_fioseq_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: wait for fio test completion
  command: 'kubectl wait --for=condition=Ready pod/{{ podlist.stdout }} -n {{ bench_fioseq_namespace }} --timeout={{ bench_fioseq_maxtime_sec }}s'

- name: create directory for storing pod output
  file: 
    path: '{{ bench_fioseq_dir }}/{{ bench_fioseq_test }}_{{ podlist.stdout }}'
    state: directory

- name: fetch output from pod 
  command: 'kubectl cp {{ bench_fioseq_namespace }}/{{ podlist.stdout }}:{{ bench_fioseq_podoutdir }} {{ bench_fioseq_dir }}/{{ bench_fioseq_test }}_{{ podlist.stdout }}'

- name: get fio pod location
  shell: 'kubectl get pods -l {{ bench_fioseq_podlabel }} -n {{ bench_fioseq_namespace }} -o wide >> {{ bench_fioseq_pdir }}/podlocations.{{ role_name }}.txt'

- name: delete fio pod
  command: 'kubectl delete -f {{ bench_fioseq_dir }}/fio_{{ bench_fioseq_test }}_job.yaml -n {{ bench_fioseq_namespace }}'

...
