---

#
# variables similar to the below are likely to be present in different bench roles
#

# output directory for run
bench_fioforsql_pdir: '{{ run_dir }}'

# directory for role's output
bench_fioforsql_dir: '{{ run_dir }}/{{ role_name }}'

# namespace
bench_fioforsql_namespace: '{{ run_namespace }}'

# label on pods
bench_fioforsql_preppodlabel: "type=benchmark-prep-pod"
bench_fioforsql_podlabel: "type=benchmark-pod"

# for nodeSelector
# bench_fioforsql_nodelabel="node-role.kubernetes.io/worker=''"


# directory where output files exist in pods/containers
bench_fioforsql_podoutdir: /benchout

# main container name
bench_fioforsql_container: "benchmark-complete"

# maximum time for a run; used for wait timeout
bench_fioforsql_maxtime_sec: 36000

#
# variables likely to be specific to this benchmark
#

# pvc size; limit on data set size
bench_fioforsql_pvcsize_gb: 16

# block size for initial write`
bench_fioforsql_txnlogfile: "txn_log"

# file sizes
bench_fioforsql_logfsz_gb: 2
bench_fioforsql_tblfsz_mb: 512

# block size for initial write
bench_fioforsql_sbs_kb: 1024

# block size for random IO
bench_fioforsql_dbbs_kb: 16

# number of jobs
bench_fioforsql_nthrds: 12

# iodepth per job
bench_fioforsql_iodepth: 2

# read/write mix
bench_fioforsql_readpct: 80

# run time for time based job
bench_fioforsql_run_sec: 120

...
