---

#
# variables similar to the below are likely to be present in different roles
#

# output directory for run
stats_sysstat_pdir: '{{ run_dir }}'

# directory for role's output
stats_sysstat_dir: '{{ run_dir }}/{{ role_name }}'

# namespace
# stats_sysstat_namespace: '{{ stats_namespace }}'
stats_sysstat_namespace: kube-system

# label on sysstat pods
stats_sysstat_podlabel: "name=sysstat-collection"

# for nodeSelector
# stats_sysstat_nodelabel: "node-role.kubernetes.io/worker=''"

# directory where output files exist in pods/containers
stats_sysstat_podoutdir: /data

#
# variables specific to this role
#

# allow dropping caches
stats_sysstat_allowdropcache: False

# default monitoring interval
stats_sysstat_interval_sec: 10

# top output can get huge
# separate knob for top mon interval
stats_sysstat_topintrvl_sec: 30

# top output can get huge
# opt to limit it by setting below to True
stats_sysstat_limittop: True

# number of top top threads for which output is collected
# when stats_sysstat_limittop is true
stats_sysstat_topthrds: 100

# number of top top procs for which output is collected
# when stats_sysstat_limittop is true
stats_sysstat_topprocs: 20

...
