---
# defaults file for stats_sysstat

# default monitoring interval
stats_sysstat_namespace: kube-system

# label on systat pods
stats_sysstat_podlabel: "name=sysstat-collection"

# directory where output files exist in pods/containers
stats_sysstat_podoutdir: /data

# default monitoring interval
stats_sysstat_interval_sec: 10

# top output can get huge
# separate knob for top mon interval
stats_sysstat_topintrvl_sec: 30

# top output can get huge
# number of top top threads for which output is collected
stats_sysstat_topthrds: 100

# top output can get huge
# number of top top procs for which output is collected
stats_sysstat_topprocs: 20

...
