---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
...
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio
spec:
  template:
    metadata:
      labels:
        type: benchmark-pod
    spec:
      volumes:
      - name: output-volume
        emptyDir: {}
      - name: fio-pv
        persistentVolumeClaim:
          claimName: fio-pv-claim
      containers:
      - name: benchmark-complete
        image: rhel7
        volumeMounts:
          - mountPath: /benchout
            name: output-volume
        command: ["/bin/sh"]
        args: ["-c", "touch /benchout/benchmark.completed.txt; sleep 3600"]
      initContainers:
      - name: fio-container
        image: quay.io/mpillai/fio
        volumeMounts:
          - mountPath: /benchout
            name: output-volume
          - mountPath: /dataset
            name: fio-pv
        command: ["/bin/sh"]
        args:
          - "-c" 
          - > 
            fio --name=writetest --rw=write 
            --ioengine=sync --direct=0 
            --create_on_open=1 --end_fsync=1 
            --directory=/dataset 
            --filename_format='f.$jobnum.$filenum'
            --bs=128k --filesize=1g --numjobs=2 
            --output=/benchout/fio.run.txt 
            ; ls -l /dataset > /benchout/fio.ls.txt
      restartPolicy: Never
...
