---

- name: get pod info
  command: 'kubectl get pods -n {{ storage_ceph_nm }} -l {{ storage_ceph_toolspodlabel }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- debug: msg='rook-ceph-tools pod not found; will skip cache drop'
  when: podlist.stdout == ""

- name: drop osd caches
  command: 'kubectl exec {{ podlist.stdout }} -n {{ storage_ceph_nm }} -- ceph tell osd.\* cache drop'
  when: podlist.stdout != ""

- name: drop mds caches
  command: 'kubectl exec {{ podlist.stdout }} -n {{ storage_ceph_nm }} -- ceph tell mds.\* cache drop'
  when: podlist.stdout != ""

...
