---

- name: create directory if not present for storing output
  file:
    path: '{{ storage_ceph_dir }}'
    state: directory

- name: get pod info
  command: 'kubectl get pods -n {{ storage_ceph_nm }} -l {{ storage_ceph_toolspodlabel }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- debug: msg='rook-ceph-tools pod not found; will skip cache drop'
  when: podlist.stdout == ""

- name: drop ceph caches
  block:
    - shell: 'date >> {{ storage_ceph_dir }}/drop_caches.start.txt'
    - command: 'kubectl exec {{ podlist.stdout }} -n {{ storage_ceph_nm }} -- ceph tell mds.\* cache drop'
    - command: 'kubectl exec {{ podlist.stdout }} -n {{ storage_ceph_nm }} -- ceph tell osd.\* cache drop'
    - shell: 'date >> {{ storage_ceph_dir }}/drop_caches.finish.txt'
  when: podlist.stdout != ""

...
