---

- set_fact:
    bench_fiorand_storageclass: '{{ run_storageclass }}'
  when: bench_fiorand_storageclass is not defined and run_storageclass is defined

- set_fact:
    server_fio_storageclass: '{{ bench_fiorand_storageclass }}'
  when: bench_fiorand_storageclass is defined

- set_fact:
    server_fio_nodelabel: '{{ bench_fiorand_servernodelabel }}'
  when: bench_fiorand_servernodelabel is defined

# calculate per-server space requirement
- set_fact:
    bench_fiorand_pvcsz_req_gb: "{{ bench_fiorand_pvcsz_scalefactor * bench_fiorand_njobs * bench_fiorand_fsz_gb + bench_fiorand_pvcsz_extra_gb }}"
  when: bench_fiorand_pvcsz_req_gb is not defined

- include_role:
    name: server_fio
  vars:
    server_mode: start
    server_fio_namespace: '{{ bench_fiorand_namespace }}'
    server_fio_nservers: '{{ bench_fiorand_ninstances }}'
    server_fio_pvcsize_gb: '{{ bench_fiorand_pvcsz_req_gb }}'

- set_fact:
    bench_fiorand_datadir: '{{ server_fio_datadir }}'
    bench_fiorand_serverlist: '{{ server_fio_serverlist.split(",") }}'

- name: create directory for storing role output
  file:
    path: '{{ bench_fiorand_dir }}'
    state: directory

- name: create job yaml from template
  template:
    src: '{{ role_path }}/templates/fioprep_job.j2'
    dest: '{{ bench_fiorand_dir }}/fioprep_job.yaml'

- name: create fioprep pod
  command: 'kubectl create -f {{ bench_fiorand_dir }}/fioprep_job.yaml -n {{ bench_fiorand_namespace }}'

- name: get pod name
  command: 'kubectl get pods -l {{ bench_fiorand_preppodlabel }} -n {{ bench_fiorand_namespace }} --no-headers -o custom-columns=":metadata.name"'
  register: podlist

- name: wait for fio prepare phase completion
  command: 'kubectl wait --for=condition=Ready pod/{{ podlist.stdout }} -n {{ bench_fiorand_namespace }} --timeout={{ bench_fiorand_maxtime_sec }}s'

- name: create directory for storing fioprep pod output
  file: 
    path: '{{ bench_fiorand_dir }}/prepare_{{ podlist.stdout }}'
    state: directory

- name: fetch output from fioprep pod
  command: 'kubectl cp {{ bench_fiorand_namespace }}/{{ podlist.stdout }}:{{ bench_fiorand_podoutdir }} {{ bench_fiorand_dir }}/prepare_{{ podlist.stdout }}'

- name: delete fioprep pod
  command: 'kubectl delete -f {{ bench_fiorand_dir }}/fioprep_job.yaml -n {{ bench_fiorand_namespace }}'
...
